imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true}
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
stof_doctrine_extensions: 
    orm: 
        default: 
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: LaNet\LaNetBundle\Entity\User
    registration:
#        confirmation:
#            enabled:    true
        form:
            type: la_user_registration
    
liip_imagine:
#    cache_prefix:         /uploads/cache
#    cache_clearer:        true

    filter_sets:
#        my_partner_thumb_small:
#            quality:              100
#            filters:
#                relative_resize: { widen: 40 }

#        my_mentor_thumb_small:
#            quality:              100
#            filters:
#                my_square_filter: { size: 40 }  

        my_news_big:
            quality:              100
            filters:
                relative_resize: { widen: 700 }
        my_event_id2:
            quality:              100
            filters:
                relative_resize: { widen: 333 }
        my_master_thumb_medium:
                    quality:              100
                    filters:
                        thumbnail: { size: [120, 120], mode: inset }
        my_thumb_portfolio:
                    quality:              100
                    filters:
                        my_square_filter: { size: 120 }
                        
        my_thumb_portfolio_large:
                    quality:              100
                    filters:
                        my_square_full_filter: { size: 800 }
        
        my_thumb_portfolio_large3:
                    quality:              100
                    filters:
                        my_square_full_filter: { size: 800 }
                        
        my_thumb_portfolio_large2:
                    quality:              100
                    filters:
                        my_square_full_filter: { size: 422 }
                        
        my_master_thumb_small:
                    quality:              100
                    filters:
                        thumbnail: { size: [60, 60], mode: inset }
       
        my_master_thumb_large:
                    quality:              100
                    filters:
#                        thumbnail: { size: [240, 240], mode: outbound }
                        my_square_filter:  { size: 240 }
        my_master_large:
                    quality:              100
                    filters:
                        thumbnail: { size: [240, 240], mode: inset }
        my_slider:
                    quality:              100
                    filters:
                        thumbnail: { size: [30], mode: inset  }                
        my_slider2:
                    quality:              100
                    filters:
                        thumbnail: { size: [106, 60], mode: outbound  }                
       
        my_slider_event:
                    quality:              100
                    filters:
                        thumbnail: { size: [320, 180], mode: outbound  }                
        my_slider3:
                    quality:              100
                    filters:
                        thumbnail: { size: [108, 61], mode: outbound }                
        my_main_page_event_big:
                    quality:              100
                    filters:
                        thumbnail: { size: [340, 192], mode: outbound }                
        my_main_page_event_small:
                    quality:              100
                    filters:
                        thumbnail: { size: [108, 61], mode: outbound }                
     
        my_main_page_test:
                    quality:              100
                    filters:
                        thumbnail: { size: [130, 130], mode: outbound } 
                        
        my_school_registration:
                    quality:              100
                    filters:
                        thumbnail: { size: [150, 150], mode: outbound } 
                        
        my_main_page_advice:
                    quality:              100
                    filters:
                        thumbnail: { size: [50, 50], mode: outbound } 
        
        my_main_page_portfolio_new:
                    quality:              100
                    filters:
                        thumbnail: { size: [120, 120], mode: outbound } 
        
        my_main_page_discounts:
                    quality:              100
                    filters:
                        thumbnail: { size: [280], mode: outbound } 
                        
        my_main_page_trust:
                    quality:              100
                    filters:
                        thumbnail: { size: [110, 110], mode: outbound }                
                       
        my_main_page_master:
                    quality:              100
                    filters:
                        thumbnail: { size: [110, 110], mode: outbound }   
                        
        my_masters_list:
                    quality:              100
                    filters:
                        thumbnail: { size: [110, 110], mode: outbound }                
                       
        my_adverts_list:
                    quality:              100
                    filters:
                        thumbnail: { size: [110, 110], mode: outbound }                
        my_school_main:
                    quality:              100
                    filters:
                        thumbnail: { size: [145, 81], mode: outbound }                
                       
     
                         
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
