# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    true
            

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/master/profile, role: ROLE_SPECIALIST }
        - { path: ^/master/change_password, role: ROLE_SPECIALIST }
        - { path: ^/school/profile, role: ROLE_SCHOOL_CENTER }
        - { path: ^/school/change_password, role: ROLE_SCHOOL_CENTER }
        - { path: ^/salon/profile, role: ROLE_SALON }
        - { path: ^/salon/change_password, role: ROLE_SALON }
        - { path: ^/agancy/profile, role: ROLE_AGANCY }
        - { path: ^/agancy/change_password, role: ROLE_AGANCY }
        - { path: ^/brand/profile, role: ROLE_BRAND }
        - { path: ^/brand/change_password, role: ROLE_BRAND }
        - { path: ^/consumer/profile, role: ROLE_CONSUMER }
        - { path: ^/consumer/change_password, role: ROLE_CONSUMER }
        - { path: ^/admin/, role: ROLE_ADMIN }