la_net_la_net_news_list:
    pattern:  /news
    defaults: { _controller: LaNetLaNetBundle:News:newsList }
    
la_net_la_net_news_id:
    pattern:  /news/{slug}
    defaults: { _controller: LaNetLaNetBundle:News:newsId }