la_net_lanet_set_regions:
    pattern:  /set_region
    defaults: { _controller: LaNetLaNetBundle:Location:setRegion }


la_net_lanet_location_cities:
    pattern:  /ajax/get_cities/{id}
    defaults: { _controller: LaNetLaNetBundle:Location:getCities }
    options:
        expose: true