la_net_la_net_salon_list:
    pattern:  /club/salon
    defaults: { _controller: LaNetLaNetBundle:Salon:list }
    
la_net_la_net_discounts_list:
    pattern:  /salon/discounts/list
    defaults: { _controller: LaNetLaNetBundle:Salon:discountList }

la_net_la_net_salon_id:
    pattern:  /salon/{id}
    defaults: { _controller: LaNetLaNetBundle:Salon:salonId }
    requirements:
        id:  \d+
    
la_net_la_net_salon_profile:
    pattern:  /salon/profile
    defaults: { _controller: LaNetLaNetBundle:Salon:profile }

la_net_la_net_salon_change_pass:
    pattern:  /salon/change_password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }

la_net_la_net_salon_profile_work:
    pattern:  /salon/profile/work
    defaults: { _controller: LaNetLaNetBundle:Salon:profileWork }

la_net_la_net_salon_profile_portfolio:
    pattern:  /salon/profile/portfolio
    defaults: { _controller: LaNetLaNetBundle:Salon:profilePortfolio }
    
la_net_la_net_salon_profile_discounts:
    pattern:  /salon/profile/discounts
    defaults: { _controller: LaNetLaNetBundle:Salon:discounts }
    
la_net_la_net_salon_profile_service_price:
    pattern:  /salon/profile/service_price
    defaults: { _controller: LaNetLaNetBundle:Salon:profileServicePrice }
    
la_net_la_net_salon_profile_discounts_isDraft:
    pattern:  /ajax/salon/profile/isDraft/{id}
    defaults: { _controller: LaNetLaNetBundle:Salon:isDraft }
        
la_net_la_net_salon_profile_discounts_edit:
    pattern:  /salon/profile/edit/{id}
    defaults: { _controller: LaNetLaNetBundle:Salon:edit }
    options:
        expose: true

la_net_la_net_salon_profile_discounts_delete:
    pattern:  /ajax/salon/profile/delete/{id}
    defaults: { _controller: LaNetLaNetBundle:Salon:delete }
    options:
        expose: true   

la_net_la_net_salon_profile_discounts_add:
    pattern:  /salon/profile/create
    defaults: { _controller: LaNetLaNetBundle:Salon:edit }
    options:
        expose: true