la_net_la_net_homepage:
    pattern:  /
    defaults: { _controller: LaNetLaNetBundle:Main:index }
    
la_net_la_net_unavailable:
    pattern:  /unavailable
    defaults: { _controller: LaNetLaNetBundle:Main:unavailable }
    
la_net_la_net_contact:
    pattern:  /contact
    defaults: { _controller: LaNetLaNetBundle:Main:contact }

la_net_la_net_validation:
    pattern:  /validation/{uniqId}
    defaults: { _controller: LaNetLaNetBundle:Brand:validation, uniqId: default_uniqId  }
    
la_net_la_net_ajax_banner:
    pattern:  /ajax/banner
    defaults: { _controller: LaNetAdminBundle:Banners:count }
    options:
        expose: true
            
la_net_la_net_about:
    pattern:  /about
    defaults: { _controller: LaNetLaNetBundle:Main:about }
    
la_net_la_net_ajax_notifications:
    pattern:  /ajax/notifications
    defaults: { _controller: LaNetLaNetBundle:Main:notifications }
    options:
        expose: true
        
la_net_la_net_homepage:
    pattern:  /
    defaults: { _controller: LaNetLaNetBundle:Main:index }
    
la_net_la_net_access_denied:
    pattern:  /access_denied
    defaults: { _controller: LaNetLaNetBundle:Main:accessDenied }
    
la_net_la_net_Master_routes:
  resource: "routing_master.yml"
  prefix: /
  
la_net_la_net_Menu_routes:
  resource: "routing_menu.yml"
  prefix: /  
  
la_net_la_net_Salon_routes:
  resource: "routing_salon.yml"
  prefix: /
  
la_net_la_net_School_routes:
  resource: "routing_school.yml"
  prefix: /
  
la_net_la_net_agancy_routes:
  resource: "routing_agancy.yml"
  prefix: /
  
la_net_la_net_consumer_routes:
  resource: "routing_consumer.yml"
  prefix: /
  
la_net_la_net_News_routes:
  resource: "routing_news.yml"
  prefix: /
  
la_net_la_net_Events_routes:
  resource: "routing_events.yml"
  prefix: /
  
la_net_la_net_Upcoming_Events_routes:
  resource: "routing_upcoming_events.yml"
  prefix: /
  
la_net_la_net_Tests_routes:
  resource: "routing_tests.yml"
  prefix: /
  
la_net_la_net_Adverts_routes:
  resource: "routing_adverts.yml"
  prefix: /
  
la_net_la_net_Trusts_routes:
  resource: "routing_trusts.yml"
  prefix: /
  
la_net_la_net_Advices_routes:
  resource: "routing_advices.yml"
  prefix: /
  
la_net_la_net_Product_routes:
  resource: "routing_product.yml"
  prefix: /
  
la_net_la_net_Location_routes:
  resource: "routing_location.yml"
  prefix: /
  
la_net_la_net_Brand_routes:
  resource: "routing_brand.yml"
  prefix: /
  
la_net_la_net_validation:
    pattern:  user/validation/{uniqId}
    defaults: { _controller: LaNetLaNetBundle:Main:validation, uniqId: default_uniqId  }
    
