la_net_la_net_ajax_menu_getBrand:
    pattern:  /ajax/master/getBrand
    defaults: { _controller: LaNetLaNetBundle:Menu:getBrand } 
    options:
        expose: true
        
la_net_la_net_ajax_menu_getProductCategory:
    pattern:  /ajax/master/getProductCategory
    defaults: { _controller: LaNetLaNetBundle:Menu:getProductCategory } 
    options:
        expose: true
        
la_net_la_net_ajax_menu_getProductSubCategory:
    pattern:  /ajax/master/getProductSubCategory
    defaults: { _controller: LaNetLaNetBundle:Menu:getProductSubCategory } 
    options:
        expose: true               

la_net_la_net_ajax_menu_getParentId:
    pattern:  /ajax/master/getParentId
    defaults: { _controller: LaNetLaNetBundle:Menu:getParentId } 
    options:
        expose: true      
        
la_net_la_net_ajax_menu_rating:
    pattern:  /ajax/rating
    defaults: { _controller: LaNetLaNetBundle:Menu:rating } 
    options:
        expose: true     
        
la_net_la_net_ajax_menu_brand_rating:
    pattern:  /ajax/rating/brand
    defaults: { _controller: LaNetLaNetBundle:Menu:ratingBrand } 
    options:
        expose: true      
        
la_net_la_net_ajax_menu_salon_rating:
    pattern:  /ajax/rating/salon
    defaults: { _controller: LaNetLaNetBundle:Menu:ratingSalon } 
    options:
        expose: true  
        
la_net_la_net_ajax_menu_school_rating:
    pattern:  /ajax/rating/school
    defaults: { _controller: LaNetLaNetBundle:Menu:ratingSchool } 
    options:
        expose: true         