la_net_la_net_product_list:
    pattern:  /products
    defaults: { _controller: LaNetLaNetBundle:Product:list }
    
la_net_la_net_product_id:
    pattern:  /products/{id}
    defaults: { _controller: LaNetLaNetBundle:Product:productId }    