parameters:
#    la_net_la_net.example.class: LaNet\LaNetBundle\Example

services:
    before_controller.listener:
        class: LaNet\LaNetBundle\EventListener\BeforeControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    user_create.listener:
        class: LaNet\LaNetBundle\EventListener\UserListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event:prePersist}
            
    la_user.registration.form.type:
        class: LaNet\LaNetBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, '@service_container']
        tags:
            - { name: form.type, alias: la_user_registration }

    la_net.reg_init:
        class: LaNet\LaNetBundle\EventListener\AutoRoleAssignmentListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }
    la_net.reg_init_confirm:
        class: LaNet\LaNetBundle\EventListener\RegistrationNotification
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }
    la_net.password_change:
        class: LaNet\LaNetBundle\EventListener\ChangePasswordListener
        arguments: [ @router, @security.context]
        tags:
            - { name: kernel.event_subscriber }  
    liip_imagine.filter.loader.my_square_filter:
        class: LaNet\LaNetBundle\ImagineFilter\Loader\MySquareFilterLoader
        tags:
          - { name: liip_imagine.filter.loader, loader: my_square_filter }
            
