la_net_admin_masters:
    pattern:  /masters
    defaults: { _controller: LaNetAdminBundle:Master:main }
    
la_net_admin_masters_list:
    pattern:  /masters/list
    defaults: { _controller: LaNetAdminBundle:Master:list }
    
la_net_admin_masters_edit_profile:
    pattern: /masters/edit/{id}
    defaults: { _controller: LaNetAdminBundle:Master:edit }

la_net_admin_reset_password:
    pattern:  /reset/{id}
    defaults: { _controller: LaNetAdminBundle:Master:reset }
    
la_net_admin_masters_ajax:
    pattern:  /ajax/masters
    defaults: { _controller: LaNetAdminBundle:Master:listAjax }
    options:
        expose: true
        
la_net_admin_ajax_delete_master:
    pattern:  /ajax/delete_master/{id}
    defaults: { _controller: LaNetAdminBundle:Master:delete }
    options:
        expose: true
        
la_net_admin_ajax_inTop_master:
    pattern:  /ajax/inTop_master/{id}
    defaults: { _controller: LaNetAdminBundle:Master:inTop }
   
la_net_admin_ajax_premium_master:
    pattern:  /ajax/premium_master/{id}
    defaults: { _controller: LaNetAdminBundle:Master:premium }
   
        
la_net_admin_masters_change_password:
    pattern:  /changepassword/{id}
    defaults: { _controller: LaNetBundle:Master:changePassword }

la_net_admin_masters_deleteAccount:
  pattern: /admin_delete/{id}
  defaults:
    _controller: LaNetAdminBundle:Master:deleteAccount
  options:
      expose: true

