la_net_admin_homepage:
    pattern:  /
    defaults: { _controller: LaNetAdminBundle:Main:index }
    
la_net_admin_news_routes:
  resource: "routing_news.yml"
  prefix: /
  
la_net_admin_masters_routes:
  resource: "routing_masters.yml"
  prefix: /
  
la_net_admin_salons_routes:
  resource: "routing_salons.yml"
  prefix: /

la_net_admin_consumers_routes:
  resource: "routing_consumers.yml"
  prefix: /
    
la_net_admin_masters_category_routes:
  resource: "routing_masters_category.yml"
  prefix: /
  
la_net_admin_brand_routes:
  resource: "routing_brand.yml"
  prefix: /
  
la_net_admin_product_category_routes:
  resource: "routing_product_category.yml"
  prefix: /
  
la_net_admin_product_routes:
  resource: "routing_product.yml"
  prefix: /
