la_net_admin_homepage:
    pattern:  /
    defaults: { _controller: LaNetAdminBundle:Main:index }
    
la_net_admin_news_routes:
  resource: "routing_news.yml"
  prefix: /
  
la_net_admin_masters_routes:
  resource: "routing_masters.yml"
  prefix: 
