la_net_admin_homepage:
    pattern:  /
    defaults: { _controller: LaNetAdminBundle:Main:index }
    
la_net_admin_send_mail:
    pattern:  /send_mail
    defaults: { _controller: LaNetAdminBundle:Main:sendMail }
    
la_net_admin_news_routes:
  resource: "routing_news.yml"
  prefix: /

la_net_admin_events_routes:
  resource: "routing_events.yml"
  prefix: /
  
la_net_admin_adverts_routes:
  resource: "routing_adverts.yml"
  prefix: /
  
la_net_admin_trusts_routes:
  resource: "routing_trusts.yml"
  prefix: /
  
la_net_admin_tests_routes:
  resource: "routing_tests.yml"
  prefix: /
  
la_net_admin_advices_routes:
  resource: "routing_advices.yml"
  prefix: /
  
la_net_admin_masters_routes:
  resource: "routing_masters.yml"
  prefix: /
  
la_net_admin_salons_routes:
  resource: "routing_salons.yml"
  prefix: /

la_net_admin_consumers_routes:
  resource: "routing_consumers.yml"
  prefix: /
    
la_net_admin_masters_category_routes:
  resource: "routing_masters_category.yml"
  prefix: /
  
la_net_admin_brand_routes:
  resource: "routing_brand.yml"
  prefix: /
  
la_net_admin_banners_routes:
  resource: "routing_banners.yml"
  prefix: /
  
la_net_admin_product_category_routes:
  resource: "routing_product_category.yml"
  prefix: /
  
la_net_admin_product_routes:
  resource: "routing_product.yml"
  prefix: /
  
la_net_admin_agancy_routes:
  resource: "routing_agancy.yml"
  prefix: /
